version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  commands:
    - echo "Installing dependencies from requirements.txt..."
    - pip install -r requirements.txt
    - echo "Installing the package itself..."
    - pip install .
    - echo "Building HTML documentation with sphinx-build..."
    - sphinx-build -b html docs/ $READTHEDOCS_OUTPUT/html  # Use the correct output path here

python:
  install:
    - requirements: requirements.txt
