version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
    - echo "Installing dependencies from requirements.txt..."
    - pip install -r requirements.txt
    - echo "Installing the package itself..."
    - pip install .
    - echo "Building HTML documentation with sphinx-build..."
    - sphinx-build -b html docs/ _build/html

python:
  install:
    - requirements: requirements.txt
    
# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py