version: 0.2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  commands:
    - pip install -r requirements.txt
    - sphinx-build -b html docs/ _build/html  # Explicit command to build docs

python:
  install:
    - requirements: requirements.txt
