version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
    - pip install -r requirements.txt
    - sphinx-build -b html docs/ _build/html  # Explicit command to build docs

python:
  install:
    - requirements: requirements.txt
    
# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: intermittent_levy/conf.py